<a href="https://colab.research.google.com/github/Purnata26/scikit/blob/master/face_emotion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#from google.colab import files
#files.upload()

In [2]:
#!mkdir -p ~/kaggle


In [3]:
#!mv /content/kaggle.json  /root/.kaggle/
#!chmod 600 ~/.kaggle/kaggle.json

In [4]:
#!pwd

In [5]:
#!kaggle competitions download -c challenges-in-representation-learning-facial-expression-recognition-challenge

In [6]:
import pandas as pd
import zipfile
from google.colab import drive

drive.mount('/content/drive/')



Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [7]:
#zip_ref = zipfile.ZipFile("/content/train.csv.zip", 'r')
#zip_ref.extractall("/content/drive/My Drive/Colab Notebooks")

#zip_ref.close()

In [9]:
import pandas as pd
data=pd.read_csv('/content/drive/My Drive/Colab Notebooks/train.csv')
data.head()

emotion                                             pixels
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1        0  151 150 147 155 148 133 111 140 170 174 182 15...
2        2  231 212 156 164 174 138 161 173 182 200 106 38...
3        4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...
4        6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...

In [10]:
pix=data.pixels.str.split(expand=True)
pix






0    1    2    3    4    5    6     ... 2297 2298 2299 2300 2301 2302 2303
0       70   80   82   72   58   58   60  ...  136  106  116   95  106  109   82
1      151  150  147  155  148  133  111  ...  108  102   67  171  193  183  184
2      231  212  156  164  174  138  161  ...  122  114  101   97   88  110  152
3       24   32   36   30   32   23   19  ...  132  133  136  139  142  143  142
4        4    0    0    0    0    0    0  ...   31   31   27   31   30   29   30
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
28704   84   85   85   85   85   85   85  ...   36   40   27  125  231  215  200
28705  114  112  113  113  111  111  112  ...  120  141  144  132  129  182  222
28706   74   81   87   89   95  100   98  ...  209  200  195  192  188  187  187
28707  222  227  203   90   86   90   84  ...  145  137  139  136  136  136  134
28708  195  199  205  206  205  203  206  ...   34    6    7    3    6   15   38

[28709 rows x 2304 columns]

In [11]:
data=data.drop('pixels',axis=1)
data

emotion
0            0
1            0
2            2
3            4
4            6
...        ...
28704        2
28705        0
28706        4
28707        0
28708        4

[28709 rows x 1 columns]

In [12]:
train_data=pd.concat([data,pix],axis=1)
train_data

emotion    0    1    2    3    4    5  ... 2297 2298 2299 2300 2301 2302 2303
0            0   70   80   82   72   58   58  ...  136  106  116   95  106  109   82
1            0  151  150  147  155  148  133  ...  108  102   67  171  193  183  184
2            2  231  212  156  164  174  138  ...  122  114  101   97   88  110  152
3            4   24   32   36   30   32   23  ...  132  133  136  139  142  143  142
4            6    4    0    0    0    0    0  ...   31   31   27   31   30   29   30
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
28704        2   84   85   85   85   85   85  ...   36   40   27  125  231  215  200
28705        0  114  112  113  113  111  111  ...  120  141  144  132  129  182  222
28706        4   74   81   87   89   95  100  ...  209  200  195  192  188  187  187
28707        0  222  227  203   90   86   90  ...  145  137  139  136  136  136  134
28708        4  195  199  205  206  205  203  ...   34    6    7    3    6   15   38

[28709 rows x 2305 columns]

In [13]:
data1=pd.read_csv('/content/drive/My Drive/Colab Notebooks/test.csv')
data1

pixels
0     254 254 254 254 254 249 255 160 2 58 53 70 77 ...
1     156 184 198 202 204 207 210 212 213 214 215 21...
2     69 118 61 60 96 121 103 87 103 88 70 90 115 12...
3     205 203 236 157 83 158 120 116 94 86 155 180 2...
4     87 79 74 66 74 96 77 80 80 84 83 89 102 91 84 ...
...                                                 ...
7173  50 36 17 22 23 29 33 39 34 37 37 37 39 43 48 5...
7174  178 174 172 173 181 188 191 194 196 199 200 20...
7175  17 17 16 23 28 22 19 17 25 26 20 24 31 19 27 9...
7176  30 28 28 29 31 30 42 68 79 81 77 67 67 71 63 6...
7177  19 13 14 12 13 16 21 33 50 57 71 84 97 108 122...

[7178 rows x 1 columns]

In [14]:
test_data=data1.pixels.str.split(expand=True)
test_data

0    1    2    3    4    5    6     ... 2297 2298 2299 2300 2301 2302 2303
0     254  254  254  254  254  249  255  ...   84   22    0    0   42  129  180
1     156  184  198  202  204  207  210  ...  193  188  184  180  172  167  161
2      69  118   61   60   96  121  103  ...   90   92   93   92   88   87   90
3     205  203  236  157   83  158  120  ...  206  196  181  112   43   82   86
4      87   79   74   66   74   96   77  ...   35   38   40   45   41   34   32
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
7173   50   36   17   22   23   29   33  ...  217  221  222  220  223  221  216
7174  178  174  172  173  181  188  191  ...  118   66    7    0    0    0    0
7175   17   17   16   23   28   22   19  ...  193  194  170  148  154  133  113
7176   30   28   28   29   31   30   42  ...   26   28   35   35   35   30   28
7177   19   13   14   12   13   16   21  ...  195  151   99  146  189  199  201

[7178 rows x 2304 columns]

In [15]:
train_data=train_data.values

In [16]:
trainX = train_data[:, 1:].reshape(train_data.shape[0],48,48,1).astype( 'float32' )

trainX

array([[[[ 70.],
         [ 80.],
         [ 82.],
         ...,
         [ 52.],
         [ 43.],
         [ 41.]],

        [[ 65.],
         [ 61.],
         [ 58.],
         ...,
         [ 56.],
         [ 52.],
         [ 44.]],

        [[ 50.],
         [ 43.],
         [ 54.],
         ...,
         [ 49.],
         [ 56.],
         [ 47.]],

        ...,

        [[ 91.],
         [ 65.],
         [ 42.],
         ...,
         [ 72.],
         [ 56.],
         [ 43.]],

        [[ 77.],
         [ 82.],
         [ 79.],
         ...,
         [105.],
         [ 70.],
         [ 46.]],

        [[ 77.],
         [ 72.],
         [ 84.],
         ...,
         [106.],
         [109.],
         [ 82.]]],


       [[[151.],
         [150.],
         [147.],
         ...,
         [129.],
         [140.],
         [120.]],

        [[151.],
         [149.],
         [149.],
         ...,
         [122.],
         [141.],
         [137.]],

        [[151.],
         [151.],
      

In [17]:
trainX.shape

(28709, 48, 48, 1)

In [18]:

X_train = trainX / 255.0
X_train

array([[[[0.27450982],
         [0.3137255 ],
         [0.32156864],
         ...,
         [0.20392157],
         [0.16862746],
         [0.16078432]],

        [[0.25490198],
         [0.23921569],
         [0.22745098],
         ...,
         [0.21960784],
         [0.20392157],
         [0.17254902]],

        [[0.19607843],
         [0.16862746],
         [0.21176471],
         ...,
         [0.19215687],
         [0.21960784],
         [0.18431373]],

        ...,

        [[0.35686275],
         [0.25490198],
         [0.16470589],
         ...,
         [0.28235295],
         [0.21960784],
         [0.16862746]],

        [[0.3019608 ],
         [0.32156864],
         [0.30980393],
         ...,
         [0.4117647 ],
         [0.27450982],
         [0.18039216]],

        [[0.3019608 ],
         [0.28235295],
         [0.32941177],
         ...,
         [0.41568628],
         [0.42745098],
         [0.32156864]]],


       [[[0.5921569 ],
         [0.5882353 ],
         [0.57

In [19]:
from keras.utils import np_utils
y_train = train_data[:,0]
y_train=np_utils.to_categorical(y_train)
y_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [20]:
y_train.shape

(28709, 7)

In [21]:
test_data=test_data.values

In [22]:
test_X=test_data[:,0:].reshape(test_data.shape[0],48,48,1).astype('float32')
test_X

array([[[[254.],
         [254.],
         [254.],
         ...,
         [ 16.],
         [  0.],
         [161.]],

        [[254.],
         [254.],
         [254.],
         ...,
         [ 17.],
         [  0.],
         [122.]],

        [[254.],
         [254.],
         [254.],
         ...,
         [ 26.],
         [  0.],
         [114.]],

        ...,

        [[ 66.],
         [ 86.],
         [ 99.],
         ...,
         [255.],
         [252.],
         [254.]],

        [[ 84.],
         [ 92.],
         [ 92.],
         ...,
         [236.],
         [255.],
         [255.]],

        [[ 93.],
         [ 90.],
         [ 85.],
         ...,
         [ 42.],
         [129.],
         [180.]]],


       [[[156.],
         [184.],
         [198.],
         ...,
         [157.],
         [154.],
         [150.]],

        [[146.],
         [182.],
         [199.],
         ...,
         [161.],
         [154.],
         [150.]],

        [[135.],
         [176.],
      

In [23]:
test_X.shape

(7178, 48, 48, 1)

In [29]:
from keras.models import Sequential
from keras.layers import Activation,Dense,Flatten,MaxPooling2D,Dropout,Conv2D
from keras.callbacks import ModelCheckpoint
model=Sequential()
model.add(Conv2D(200,(3,3),input_shape=X_train.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(100,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(100,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dropout(0.2))
model.add(Dense(64,activation='relu'))
#Dense layer of 64 neurons
model.add(Dense(7,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [30]:
checkpoint = ModelCheckpoint('model-{epoch:03d}.model',monitor='val_loss',verbose=0,save_best_only=True,mode='auto')

model.fit(X_train,y_train,epochs=5,batch_size=1,callbacks=[checkpoint],validation_split=0.2)

Epoch 1/5
22967/22967 [==============================] - 551s 24ms/step - loss: 1.7669 - accuracy: 0.2771 - val_loss: 1.6517 - val_accuracy: 0.3488
Epoch 2/5
22967/22967 [==============================] - 542s 24ms/step - loss: 1.6133 - accuracy: 0.3633 - val_loss: 1.5909 - val_accuracy: 0.3800
Epoch 3/5
22967/22967 [==============================] - 547s 24ms/step - loss: 1.5496 - accuracy: 0.3956 - val_loss: 1.4807 - val_accuracy: 0.4206
Epoch 4/5
22967/22967 [==============================] - 542s 24ms/step - loss: 1.5117 - accuracy: 0.4108 - val_loss: 1.4674 - val_accuracy: 0.4258
Epoch 5/5
22967/22967 [==============================] - 534s 23ms/step - loss: 1.4852 - accuracy: 0.4203 - val_loss: 1.4678 - val_accuracy: 0.4293


In [ ]:
model.summary()