<a href="https://colab.research.google.com/github/Purnata26/scikit/blob/master/kaggle_f_detect.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import os,cv2
import numpy as np
data_path='/content/drive/My Drive/Face Mask Dataset/Train'
catagory=os.listdir(data_path)
labels=np.arange(len(catagory))
label_dict=dict(zip(catagory,labels))
label_dict

{'WithMask': 0, 'WithoutMask': 1}

In [ ]:
test_data_path='/content/drive/My Drive/Face Mask Dataset/Validation'
test_catagory=os.listdir(test_data_path)
test_label=np.arange(len(test_catagory))
label_dict_test=dict(zip(test_catagory,test_label))
label_dict_test

{'WithMask': 0, 'WithoutMask': 1}

In [ ]:
img_size=100
target=[]
all_img=[]

for i in catagory:
  file_path=os.path.join(data_path,i)
  img_names=os.listdir(file_path)
  for j in img_names:
    img_path=os.path.join(file_path,j)
    img=cv2.imread(img_path)
    try:

      gray=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
      #covert img in gray scale
      resized=cv2.resize(gray,(img_size,img_size))
      #resize image to 100,100
      all_img.append(resized)
      target.append(label_dict[i])
    
      
    except Exception as e:
      print('Exception:',e)

all_img                


[array([[177, 173, 167, ..., 112, 109, 107],
        [179, 175, 170, ..., 112, 109, 107],
        [182, 179, 175, ..., 112, 110, 108],
        ...,
        [115, 107,  95, ...,  95,  97,  99],
        [137, 128, 115, ...,  97,  99, 100],
        [150, 141, 127, ...,  98, 100, 101]], dtype=uint8),
 array([[48, 48, 49, ..., 41, 45, 47],
        [51, 51, 51, ..., 41, 44, 45],
        [61, 60, 56, ..., 39, 39, 39],
        ...,
        [ 9,  8,  7, ...,  0,  0,  0],
        [12, 12, 12, ...,  0,  1,  1],
        [14, 14, 13, ...,  0,  1,  1]], dtype=uint8),
 array([[129, 117,  66, ...,  23,  23,  23],
        [100, 106,  55, ...,  22,  22,  22],
        [111, 106,  51, ...,  22,  22,  22],
        ...,
        [ 24,  26,  38, ..., 119,  81,  68],
        [ 25,  24,  38, ..., 108,  97,  77],
        [ 27,  24,  38, ..., 100, 119,  93]], dtype=uint8),
 array([[231, 232, 235, ..., 174, 183, 195],
        [232, 231, 232, ..., 179, 186, 176],
        [233, 232, 233, ..., 179, 178, 182],
       

In [ ]:
img_size=100
test_images=[]
test_image_label=[]
for i in test_catagory:
  folder=os.path.join(test_data_path,i)
  types=os.listdir(folder)
  for j in types:
    image_path=os.path.join(folder,j)
    image=cv2.imread(image_path)
    try:
      gray=cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
      resized=cv2.resize(gray,(img_size,img_size))
      test_images.append(resized)
      test_image_label.append(label_dict_test[i])
    except Exception as e:
      print('exeption')
test_images
    



[array([[ 9, 10, 13, ..., 60, 54, 50],
        [16, 16, 17, ..., 60, 55, 50],
        [15, 15, 15, ..., 59, 54, 49],
        ...,
        [25, 26, 26, ..., 12, 12, 12],
        [25, 26, 26, ..., 12, 12, 12],
        [25, 26, 26, ..., 12, 12, 12]], dtype=uint8),
 array([[200, 195, 185, ...,  28,  39,  44],
        [197, 192, 183, ...,  28,  36,  41],
        [191, 187, 180, ...,  29,  32,  34],
        ...,
        [ 55,  61,  74, ...,  12,   9,   7],
        [ 51,  60,  78, ...,  10,   9,   8],
        [ 49,  59,  80, ...,   9,   9,   9]], dtype=uint8),
 array([[ 56,  45,  63, ...,  44,  48,  38],
        [ 42,  36,  39, ...,  34,  44,  47],
        [ 27,  23,  34, ...,  17,  31,  51],
        ...,
        [ 41,  43,  45, ..., 147, 185, 193],
        [ 41,  42,  45, ..., 141, 159, 194],
        [ 41,  42,  45, ..., 187, 150, 178]], dtype=uint8),
 array([[ 36,  36,  35, ...,  27,  30,  30],
        [ 36,  36,  35, ...,  27,  30,  30],
        [ 35,  35,  34, ...,  25,  27,  27],
       

In [ ]:

test_images=np.array(test_images)/255
test_images=np.reshape(test_images,(test_images.shape[0],img_size,img_size,1))
test_image_label=np.array(test_image_label)
from keras.utils import np_utils
test_image_label=np_utils.to_categorical(test_image_label)
print(test_images.shape)
print(test_image_label.shape)

(800, 100, 100, 1)
(800, 2)


In [ ]:
all_img=np.array(all_img)/255
all_img=np.reshape(all_img,(all_img.shape[0],img_size,img_size,1))
target=np.array(target)
from keras.utils import np_utils
new=np_utils.to_categorical(target)
all_img.shape

(6330, 100, 100, 1)

In [ ]:
new.shape

(6330, 2)

In [ ]:
data=all_img
data.shape
target=new

In [ ]:
from keras.models import Sequential
from keras.layers import Activation,Dense,Flatten,Dropout,Conv2D,MaxPooling2D
from keras.callbacks import ModelCheckpoint
model=Sequential()
model.add(Conv2D(32,(3,3),input_shape=data.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(64,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dropout(0.2))
model.add(Dense(64,activation='relu'))
#Dense layer of 64 neurons
model.add(Dense(2,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 98, 98, 32)        320       
_________________________________________________________________
activation_2 (Activation)    (None, 98, 98, 32)        0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 49, 49, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 47, 47, 64)        18496     
_________________________________________________________________
activation_3 (Activation)    (None, 47, 47, 64)        0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 23, 23, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 33856)            

In [ ]:
model.fit(data,target,epochs=3,batch_size=1,validation_split=0.1)

Epoch 1/3
5697/5697 [==============================] - 18s 3ms/step - loss: 0.1582 - accuracy: 0.9489 - val_loss: 0.0273 - val_accuracy: 0.9937
Epoch 2/3
5697/5697 [==============================] - 18s 3ms/step - loss: 0.0824 - accuracy: 0.9733 - val_loss: 0.0501 - val_accuracy: 0.9842
Epoch 3/3
5697/5697 [==============================] - 18s 3ms/step - loss: 0.0676 - accuracy: 0.9744 - val_loss: 0.0333 - val_accuracy: 0.9874


In [ ]:
model.predict(test_images,batch_size=1)

array([[9.9606091e-01, 3.9391061e-03],
       [9.0707815e-01, 9.2921868e-02],
       [3.1541378e-05, 9.9996841e-01],
       ...,
       [7.9110287e-06, 9.9999213e-01],
       [3.0450130e-07, 9.9999964e-01],
       [1.0250774e-02, 9.8974925e-01]], dtype=float32)

In [ ]:
model.evaluate(test_images,test_image_label,batch_size=1)

800/800 [==============================] - 2s 2ms/step - loss: 0.1295 - accuracy: 0.9663


[0.1294851005077362, 0.9662500023841858]

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])