In [1]:
import pandas as pd
sms=pd.read_table('sms.tsv',names=['label','message'])

In [2]:
sms.head(10)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [3]:
sms['label_n']=sms.label.map({'ham':0,'spam':1})
sms.head()

label                                            message  label_n
0   ham  Go until jurong point, crazy.. Available only ...        0
1   ham                      Ok lar... Joking wif u oni...        0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        1
3   ham  U dun say so early hor... U c already then say...        0
4   ham  Nah I don't think he goes to usf, he lives aro...        0

In [4]:
X=sms.message
y=sms.label_n

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1)
print(X_train.shape)
print(y_train.shape)

(4179,)
(4179,)


from sklearn.feature_extraction import CountVectorizer()
vect=CountVectorizer()
vect.fit(X_train)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer() 
vect.fit(X_train)
X_train_dtm=vect.fit_transform(X_train)
pd.DataFrame(X_train_dtm.toarray(),columns=vect.get_feature_names())

00  000  008704050406  0121  01223585236  01223585334  0125698789  02  \
0      0    0             0     0            0            0           0   0   
1      0    0             0     0            0            0           0   0   
2      0    0             0     0            0            0           0   0   
3      0    0             0     0            0            1           0   0   
4      0    0             0     0            0            0           0   0   
...   ..  ...           ...   ...          ...          ...         ...  ..   
4174   0    0             0     0            0            0           0   0   
4175   0    0             0     0            0            0           0   0   
4176   0    0             0     0            0            0           0   0   
4177   0    0             0     0            0            0           0   0   
4178   0    0             0     0            0            0           0   0   

      0207  02072069400  ...  zed  zeros  zhong  zindgi  zoe  zoom  zouk  \
0        0            0  ...    0      0      0       0    0     0     0   
1        0            0  ...    0      0      0       0    0     0     0   
2        0            0  ...    0      0      0       0    0     0     0   
3        0            0  ...    0      0      0       0    0     0     0   
4        0            0  ...    0      0      0       0    0     0     0   
...    ...          ...  ...  ...    ...    ...     ...  ...   ...   ...   
4174     0            0  ...    0      0      0       0    0     0     0   
4175     0            0  ...    0      0      0       0    0     0     0   
4176     0            0  ...    0      0      0       0    0     0     0   
4177     0            0  ...    0      0      0       0    0     0     0   
4178     0            0  ...    0      0      0       0    0     0     0   

      zyada  èn  〨ud  
0         0   0    0  
1         0   0    0  
2         0   0    0  
3         0   0    0  
4         0   0    0  
...     ...  ..  ...  
4174      0   0    0  
4175      0   0    0  
4176      0   0    0  
4177      0   0    0  
4178      0   0    0  

[4179 rows x 7456 columns]

In [7]:
X_test_dtm=vect.transform(X_test)
X_test_dtm

<1393x7456 sparse matrix of type '<class 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

In [8]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb.fit(X_train_dtm,y_train)

MultinomialNB()

In [9]:
y_pred=nb.predict(X_test_dtm)

In [10]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred)

0.9885139985642498

In [11]:
metrics.confusion_matrix(y_test,y_pred)

array([[1203,    5],
       [  11,  174]], dtype=int64)

In [12]:
X_test[(y_pred==1)&(y_test==1)]

147     FreeMsg Why haven't you replied to my text? I'...
4517    Congrats! 2 mobile 3G Videophones R yours. cal...
3316    FREE MESSAGE Activate your 500 FREE Text Messa...
1929    Call from 08702490080 - tells u 2 call 0906635...
1745    Someone has conacted our dating service and en...
                              ...                        
5178    SMS AUCTION - A BRAND NEW Nokia 7250 is up 4 a...
1961    Guess what! Somebody you know secretly fancies...
1714    Hard LIVE 121 chat just 60p/min. Choose your g...
1463    09066362231 URGENT! Your mobile No 07xxxxxxxxx...
1793    WIN: We have a winner! Mr. T. Foley won an iPo...
Name: message, Length: 174, dtype: object

In [13]:
X_test[y_pred>y_test]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: message, dtype: object

In [14]:
y_pred_prob=nb.predict_proba(X_test_dtm)[:,1]

In [15]:
    metrics.roc_auc_score(y_test,y_pred_prob)

0.9866431000536962

In [16]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()

In [17]:
logreg.fit(X_train_dtm,y_train)

LogisticRegression()

In [18]:
y_pred=logreg.predict(X_test_dtm)
y_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [19]:
metrics.accuracy_score(y_test,y_pred)

0.9877961234745154

In [20]:
y_pred_prob=logreg.predict_proba(X_test_dtm)[:,1]
metrics.roc_auc_score(y_test,y_pred_prob)

0.9936280651512441

In [21]:
X_train_token=vect.get_feature_names()
print(X_train_token[0:50])

['00', '000', '008704050406', '0121', '01223585236', '01223585334', '0125698789', '02', '0207', '02072069400', '02073162414', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07', '07008009200', '07090201529', '07090298926', '07123456789', '07732584351', '07734396839', '07742676969', '0776xxxxxxx', '07781482378', '07786200117', '078', '07801543489', '07808', '07808247860', '07808726822', '07815296484', '07821230901', '07880867867', '0789xxxxxxx', '07946746291', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705']


In [22]:
nb.feature_count_


array([[ 0.,  0.,  0., ...,  1.,  1.,  1.],
       [ 5., 23.,  2., ...,  0.,  0.,  0.]])

In [23]:
nb.feature_count_.shape

(2, 7456)

In [24]:
ham_token=nb.feature_count_[0,:]
ham_token

array([0., 0., 0., ..., 1., 1., 1.])

In [25]:
spam_token=nb.feature_count_[1,:]

In [26]:
tokens=pd.DataFrame({'Token':X_train_token,'ham':ham_token,'spam':spam_token})

In [27]:
nb.class_count_

array([3617.,  562.])

In [28]:
tokens['ham']=tokens.ham+1
tokens['spam']=tokens.spam+1
tokens.sample(5,random_state=6)

Token   ham  spam
6977          very  65.0   3.0
4521         nasty   2.0   2.0
6999         villa   1.0   2.0
1266       beloved   2.0   1.0
6522  textoperator   1.0   3.0

In [29]:
tokens['ham']=tokens.ham/nb.class_count_[0]
tokens['spam']=tokens.spam/nb.class_count_[1]
tokens.sample(5,random_state=6)

Token       ham      spam
6977          very  0.017971  0.005338
4521         nasty  0.000553  0.003559
6999         villa  0.000276  0.003559
1266       beloved  0.000553  0.001779
6522  textoperator  0.000276  0.005338

In [30]:
tokens['spam_ratio']=tokens.spam/tokens.ham
tokens.sample(5,random_state=6)

Token       ham      spam  spam_ratio
6977          very  0.017971  0.005338    0.297044
4521         nasty  0.000553  0.003559    6.435943
6999         villa  0.000276  0.003559   12.871886
1266       beloved  0.000553  0.001779    3.217972
6522  textoperator  0.000276  0.005338   19.307829

In [31]:
tokens.sort_values('spam_ratio',ascending=False)

Token       ham      spam  spam_ratio
1766       claim  0.000276  0.158363  572.798932
5209       prize  0.000276  0.135231  489.131673
293         150p  0.000276  0.087189  315.361210
6680        tone  0.000276  0.085409  308.925267
3139  guaranteed  0.000276  0.076512  276.745552
...          ...       ...       ...         ...
2066          da  0.032900  0.001779    0.054084
5824         she  0.035665  0.001779    0.049891
3244          he  0.047000  0.001779    0.037858
4093          lt  0.064142  0.001779    0.027741
3135          gt  0.064971  0.001779    0.027387

[7456 rows x 4 columns]

In [32]:
tokens.index=tokens.Token
tokens.loc['dating','spam_ratio']

83.66725978647686